Gatebox fix v2
blebox/blebox_uniapi pull request #126
Opened 2021-05-24 07:10 UTC by jkarnasiewicz

1. This solution don't require additional changes in homeassistant/components/blebox/const.py in comparison to version 1, but it's more obscure and ugly.
2. I left in code comments, additional notes and questions.

2021-05-25 09:06 UTC, bbx-jp commented on blebox_uniapi/cover.py
> +    """Previous class name: Slider, is it problem if I renamed it ?"""
It's okay.

2021-05-25 22:08 UTC, gralin commented
Should fix: https://github.com/blebox/blebox_uniapi/issues/122

2021-05-28 07:53 UTC, bbx-jp requested changes
Up

2021-05-28 09:05 UTC, jkarnasiewicz commented on blebox_uniapi/cover.py
> +        return 2  # manually stopped
Done.

2021-05-28 09:08 UTC, merged